#!/bin/bash

echo "Installing flowR addin..."

Rscript -e "install.packages('remotes', repos = 'https://cloud.r-project.org')"

Rscript -e "if (Sys.getenv('GITHUB_ACCESS_TOKEN') != '') Sys.setenv(GITHUB_PAT = Sys.getenv('GITHUB_ACCESS_TOKEN')); remotes::install_github('flowr-analysis/rstudio-addin-flowr@v0.1.2')"

# Create the .Rprofile file with working directory logic
cat <<EOF > /home/jovyan/.Rprofile
set_wd <- function(path) {
  try(if (dir.exists(path)) setwd(path), silent = TRUE)
}

retry_setwd <- function(path, delay = 2, attempts = 3) {
  attempt <- function(remaining) {
    later::later(function() {
      if (interactive() && Sys.getenv("RSTUDIO") == "1") {
        set_wd(path)
      } else if (remaining > 0) {
        attempt(remaining - 1)
      }
    }, delay)
  }
  attempt(attempts)
}

retry_setwd("/home/jovyan/7h94n_src/MalawiEarlyHumanChronology/Malawi")

EOF
